const $ = selector => document.querySelector(selector);
const format = n => Number(n || 0).toLocaleString('tr-TR');
const names = {snake:'Snake',blockdrop:'Block Drop',mazechase:'Maze Chase',blastgrid:'Blast Grid',spaceshooter:'Space Shooter',darwin:'macOS',linux:'Linux',windows:'Windows'};
function cell(parent,tag,text){const el=document.createElement(tag);el.textContent=text;parent.append(el);return el;}
function pair(parent,label,value){const row=document.createElement('div');row.className='pair';cell(row,'span',label);cell(row,'strong',format(value));parent.append(row);}
function distribution(selector,values){const parent=$(selector);parent.replaceChildren();for(const [name,n] of Object.entries(values||{}))pair(parent,names[name]||name,n);if(!Object.keys(values||{}).length)cell(parent,'p','Henüz veri yok.');}
function show(data){
 const c=data.client,w=data.website,d=data.downloads;const latest=d?.samples?.at(-1);const cards=$('#cards');cards.replaceChildren();
 for(const [label,n,detail] of [['Günlük aktif kurulum',c.dau,'İstatistik paylaşımı açık · UTC bugün'],['Haftalık aktif kurulum',c.wau,'Son 7 takvim günü'],['Aylık aktif kurulum',c.mau,'Son 30 takvim günü'],['Paket indirmeleri',latest?.total,'GitHub dosya sayaçları · benzersiz kişi değil']]){const el=document.createElement('div');el.className='card';cell(el,'span',label);cell(el,'strong',latest||label!=='Paket indirmeleri'?format(n):'—');cell(el,'small',detail);cards.append(el);}
 const chart=$('#chart');chart.replaceChildren();const max=Math.max(1,...c.days.map(d=>d.active));for(const day of c.days){const bar=document.createElement('div');bar.className='bar';bar.style.setProperty('--height',Math.max(2,day.active/max*175)+'px');bar.title=day.date+': '+format(day.active)+' aktif kurulum';bar.setAttribute('role','img');bar.setAttribute('aria-label',bar.title);chart.append(bar);}
 const funnel=$('#funnel');funnel.replaceChildren();for(const [label,n] of [['İzinli site ziyaretleri',w.site_visits],['Kurulum komutu kopyalama',w.install_copies],['İzinli uygulama açılışları',c.app_opens],['İzinli kurulumlar',c.installations],['Birden fazla gün dönen kurulumlar',c.returning],['Başlayan oyun oturumları',Object.values(c.games).reduce((s,g)=>s+g.starts,0)]])pair(funnel,label,n);
 const games=$('#games');games.replaceChildren();for(const [id,name] of Object.entries(names).filter(([id])=>['snake','blockdrop','mazechase','blastgrid', 'spaceshooter'].includes(id))){const g=c.games[id]||{};const row=document.createElement('tr');for(const value of [name,...['starts','finished','left','closed','unfinished'].map(k=>format(g[k])),(g.mean_seconds||0).toFixed(1)+' sn',(g.median_seconds||0).toFixed(1)+' sn'])cell(row,'td',value);games.append(row);}
 distribution('#platforms',c.platforms);distribution('#versions',c.versions);distribution('#download-platforms',latest?.platforms);distribution('#download-versions',latest?.versions);
 $('#download-status').textContent=latest?'Son örnekleme: '+new Date(latest.at).toISOString()+(d.error?' · '+d.error:''):'İndirme sayacı henüz alınmadı.';
 const history=$('#download-history');history.replaceChildren();for(const sample of (d?.samples||[]).slice(-24).reverse()){const row=document.createElement('tr');cell(row,'td',new Date(sample.at).toISOString());cell(row,'td',format(sample.total));history.append(row);}
 $('#status').textContent='Güncellendi: '+new Date(data.generated_at).toISOString();
}
async function refresh(){const button=$('#refresh');button.disabled=true;try{const response=await fetch('/admin/api/metrics',{cache:'no-store',credentials:'same-origin',signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error();show(await response.json());}catch{$('#status').textContent='Veriler alınamadı. Erişim yetkisini ve sunucuyu kontrol edin.';}finally{button.disabled=false;}}
$('#refresh').addEventListener('click',refresh);refresh();
